version: '3.8'

services:
  admin:
    build: .
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    networks:
      - jobtrack

  # This would be your main API service
  api:
    # Assuming your main app can be containerized
    # build: ../my-job-track
    image: your-api-image:latest
    ports:
      - "8787:8787"
    environment:
      - NODE_ENV=production
    networks:
      - jobtrack

networks:
  jobtrack:
    driver: bridge

volumes:
  admin_data:
    driver: local
